---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 11

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04
  - name: debian-8.0
  - name: fedora-21
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
    attributes:
      java_se:
        force_i586: true

suites:
  - name: java_se
    run_list:
      - recipe[java_se::default]
    attributes:
      java_se:
        uri: http://10.0.0.2:4567
